// ================= FILE: src/config.js =================
// COMPLEET centrale configuratie voor ARS-U Platform v2

export const ENV = {
  NODE_ENV: process.env.NODE_ENV || 'development',
  VERCEL: !!process.env.VERCEL,
  PRODUCTION: process.env.NODE_ENV === 'production',
  LOCAL: !process.env.VERCEL
};

export const API_KEYS = {
  BITGET_API_KEY: process.env.BITGET_API_KEY || '',
  BITGET_SECRET_KEY: process.env.BITGET_SECRET_KEY || '',
  BITGET_PASSPHRASE: process.env.BITGET_PASSPHRASE || '',
  REDIS_URL: process.env.REDIS_URL || 'redis://localhost:6379',
  DISCORD_WEBHOOK_URL: process.env.DISCORD_WEBHOOK_URL || '',
  CRON_SECRET: process.env.CRON_SECRET || '',
  ADMIN_TOKEN: process.env.ADMIN_TOKEN || ''
};

export const TRADING = {
  SIDE: 'SHORT',
  NAMESPACE: 'SHORT',
  PREFIX: 'SHORT:',
  PERSISTENT_KEY: 'SHORT_LIVE',
  MODE: 'VIRTUAL'
};

export const TAXONOMY = {
  SETUP_ORDER: ['BREAKOUT', 'RETEST', 'SWEEP_REVERSAL', 'CONTINUATION', 'COMPRESSION'],
  REGIME_ORDER: ['TREND', 'CHOP', 'SQUEEZE'],
  CONFIRMATION_PROFILE_ORDER: [
    'A_STRONG_ALIGN', 'B_FLOW_ALIGN', 'C_VOLUME_ALIGN', 'D_MIXED_OK', 'E_WEAK_CONTRA'
  ],
  CHILD_FAMILIES_COUNT: 75,
  CHILD_FAMILY_SCHEMA: 'FIXED_TAXONOMY_75',
  PARENT_FAMILIES_COUNT: 15,
  PARENT_FAMILY_SCHEMA: 'FIXED_TAXONOMY_15'
};

export const ROTATION = {
  MIN_COMPLETED_FOR_ROTATION: 20,
  TARGET_FAMILIES_PER_ROTATION: 42,
  ROTATION_SCHEDULE: '0 0 * * 1',
  FREEZE_SCHEDULE: '0 22 * * 0',
  SELECTION_METHOD: 'BALANCED_SCORE',
  HYSTERESIS_THRESHOLD: 0.05,
  CONFIRMATION_LOOKBACK_HOURS: 24
};

export const RISK = {
  DEFAULT_RISK_PCT: 0.01,
  MAX_ACCOUNT_RISK_PERCENT: 0.05,
  MAX_DRAWDOWN_ALLOWED: 0.20,
  MAX_CONSECUTIVE_LOSSES: 5,
  KELLY_FRACTION: 0.25,
  MAX_KELLY_FRACTION: 0.25,
  MAX_OPEN_POSITIONS_GLOBAL: 42,
  MAX_POSITIONS_PER_FAMILY: 2,
  MIN_SAMPLE_SIZE_FOR_FAMILY: 20,
  MIN_RR_RATIO: 1.5,
  MIN_VOLATILITY: 0.005,
  MAX_VOLATILITY: 0.10
};

export const COSTS = {
  BITGET_TAKER_FEE: 0.0015,
  ENTRY_FEE: 0.0015,
  EXIT_FEE: 0.0015,
  TOTAL_ROUNDTRIP_FEE: 0.003,
  ENTRY_SLIPPAGE_PCT: 0.0005,
  EXIT_SLIPPAGE_PCT: 0.001,
  COST_PER_R_ENTRY: 0.0015,
  COST_PER_R_EXIT: 0.003
};

export const MARKET = {
  BASE_TIMEFRAME: '1H',
  LOOKBACK_PERIODS: { SHORT: 20, MEDIUM: 50, LONG: 200 },
  SYMBOLS_TO_SCAN: 500,
  MIN_CANDLES_FOR_ANALYSIS: 30,
  SCAN_INTERVAL_MS: 5 * 60 * 1000,
  PRODUCT_TYPE: 'usdt-futures',
  QUOTE_ASSET: 'USDT'
};

export const INDICATORS = {
  RSI_PERIOD: 14,
  RSI_OVERBOUGHT: 70,
  RSI_OVERSOLD: 30,
  RSI_EXTREME_HIGH: 80,
  RSI_EXTREME_LOW: 20,
  BB_PERIOD: 20,
  BB_STD_DEV: 2,
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,
  ATR_PERIOD: 14,
  VOLUME_PERIOD: 20,
  EMA_FAST: 12,
  EMA_SLOW: 26
};

export const TRADING_RULES = {
  ENABLE_BREAKOUT_VALIDATION: true,
  ENABLE_FAKE_BREAKOUT_DETECTION: true,
  ENABLE_REVERSAL_RISK_CHECK: true,
  ENABLE_DIVERGENCE_CHECK: true,
  TAKE_PROFIT_HARD_RULE: true,
  STOP_LOSS_HARD_RULE: true,
  BREAKEVEN_PROTECTION: true,
  TRAILING_STOP_ENABLED: false,
  MAX_POSITION_DURATION_HOURS: 168,
  POSITION_TIMEOUT_ACTION: 'EXIT_AT_MARKET'
};

export const SCORING = {
  FAIR_WEIGHT: 100,
  SAMPLE_REL_WEIGHT: 25,
  LOG_TOTAL_R_WEIGHT: 12,
  LOG_AVG_R_WEIGHT: 8,
  PROFIT_FACTOR_WEIGHT: 8,
  NEAR_TP_WEIGHT: 4,
  REACHED_ONE_R_WEIGHT: 4,
  DIRECT_SL_PENALTY: 35,
  NEAR_TP_THEN_LOSS_PENALTY: 15,
  GAVE_BACK_AFTER_ONE_R_PENALTY: 10,
  AVG_COST_R_PENALTY: 8,
  MIN_SAMPLE_FOR_FAIR: 5,
  SAMPLE_CONFIDENCE_CAP: 50
};

export const DISCORD = {
  ENABLED: true,
  WEBHOOK_URL: API_KEYS.DISCORD_WEBHOOK_URL,
  ALERT_TYPES: {
    SCAN_RESULT: { emoji: '🔍', color: 0x00d4ff },
    ENTRY: { emoji: '✅', color: 0x00ff88 },
    EXIT: { emoji: '🎯', color: 0x00ff88 },
    STOP_LOSS: { emoji: '🛑', color: 0xff4444 },
    ERROR: { emoji: '⚠️', color: 0xff8800 },
    HALT: { emoji: '⛔', color: 0xff4444 },
    ROTATION: { emoji: '🔄', color: 0x00d4ff },
    TRADE_UPDATE: { emoji: '📈', color: 0x00ff88 },
    SYSTEM_INFO: { emoji: 'ℹ️', color: 0x0088ff }
  },
  SEND_ALL_ENTRIES: true,
  SEND_ALL_EXITS: true,
  SEND_ERROR_ALERTS: true,
  SEND_HALT_ALERTS: true,
  SEND_ROTATION_ALERTS: true,
  SEND_SUMMARY_REPORTS: true
};

export const REDIS = {
  URL: API_KEYS.REDIS_URL,
  TIMEOUT_MS: 30000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY_MS: 1000,
  EXPIRATION: {
    SCAN_SNAPSHOT: 60 * 60,
    WEATHER: 5 * 60,
    POSITION: null,
    STATS: 24 * 60 * 60,
    ROTATION: 7 * 24 * 60 * 60
  }
};

export const API = {
  BITGET_BASE_URL: 'https://api.bitget.com/v2',
  BITGET_TIMEOUT: 30000,
  BITGET_RATE_LIMIT: 100,
  MAX_EXECUTION_TIME: 60000,
  RETRY_ATTEMPTS: 3,
  RETRY_DELAY_MS: 500,
  RATE_LIMIT_ENABLED: true,
  REQUESTS_PER_MINUTE: 100
};

export const LOGGING = {
  LEVEL: process.env.LOG_LEVEL || 'INFO',
  ENABLE_CONSOLE: true,
  ENABLE_FILE: false,
  LOG_TRADES: true,
  LOG_POSITIONS: true,
  LOG_FAMILY_UPDATES: true,
  LOG_ROTATION: true,
  LOG_ERRORS: true
};

export const ADMIN = {
  AUTH_ENABLED: true,
  ADMIN_TOKEN: API_KEYS.ADMIN_TOKEN,
  CRON_SECRET: API_KEYS.CRON_SECRET,
  ALLOW_FACTORY_RESET: true,
  ALLOW_MANUAL_ENTRY: false,
  ALLOW_MANUAL_EXIT: true,
  REQUIRE_CONFIRMATION: true
};

export const MONITORING = {
  HEALTH_CHECK_INTERVAL: 5 * 60 * 1000,
  ALERT_DRAWDOWN_THRESHOLD: 0.15,
  ALERT_LOSS_STREAK: 3,
  ALERT_POSITION_DURATION: 7 * 24 * 60 * 60 * 1000,
  CHECK_REDIS: true,
  CHECK_BITGET_API: true,
  CHECK_DISCORD_WEBHOOK: true
};

export const FEATURES = {
  ENABLE_SCANNER: true,
  ENABLE_TRADE_SYSTEM: true,
  ENABLE_ANALYTICS: true,
  ENABLE_ROTATION: true,
  ENABLE_DISCORD_ALERTS: true,
  ENABLE_ADMIN_DASHBOARD: true,
  LEARNING_MODE: true,
  SHADOW_TRADING: true,
  BACKTEST_MODE: false
};

export const CONFIG = {
  ENV, API_KEYS, TRADING, TAXONOMY, ROTATION, RISK, COSTS, MARKET, INDICATORS,
  TRADING_RULES, SCORING, DISCORD, REDIS, API, LOGGING, ADMIN, MONITORING, FEATURES
};

export default CONFIG;
